name: 'curso_data_eng'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  curso_data_eng:
    staging:
      +database: ALUMNO15_DEV_SILVER_DB
      +materialized: view

    marts:
      +database: ALUMNO15_DEV_GOLD_DB
      +materialized: table